on: [push, pull_request]
name: Continuous Integration

jobs:
  build:
    name: Test (Linux, ubuntu-latest, SingleThread)
    runs-on: ubuntu-latest
    steps:
        - name: Checkout
          uses: actions/checkout@v3

        - name: Setup Node
          uses: actions/setup-node@v3
          with:
            node-version: "16"

        - name: Initialize Node
          run: npm ci

        - name: Run build script
          run: npm run build --if-present
